/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ss_crswrk;

import java.awt.event.ActionEvent;
import javax.swing.DefaultListModel;



/**
 *
 * @author Daniel
 */
public class window extends javax.swing.JFrame {

    
    DefaultListModel<String> registerListModel;
    DefaultListModel<String> friendsListModel;
    
    /**
     * Creates new form window
     */
    public window() {
        registerListModel = new DefaultListModel<String>();
        friendsListModel = new DefaultListModel<String>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        parentPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        usernameLbl = new javax.swing.JLabel();
        goToRegisterBtn = new javax.swing.JButton();
        passwordLbl = new javax.swing.JLabel();
        usernameTxtFld = new javax.swing.JTextField();
        passwordTxtFld = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        registerPanel = new javax.swing.JPanel();
        rUsernameLbl = new javax.swing.JLabel();
        backToLoginBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        orLbl = new javax.swing.JLabel();
        PoBLbl = new javax.swing.JLabel();
        DoBLbl = new javax.swing.JLabel();
        rUsernameTxtFld = new javax.swing.JTextField();
        PoBTxtFld = new javax.swing.JTextField();
        DoBTxtFld = new javax.swing.JTextField();
        musicDropdown = new javax.swing.JComboBox<>();
        addBtn = new javax.swing.JButton();
        musicProfileLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        deleteBtn = new javax.swing.JButton();
        homePanel = new javax.swing.JPanel();
        friendSection = new javax.swing.JPanel();
        friendsLbl = new javax.swing.JLabel();
        friendsList = new javax.swing.JScrollPane();
        friendsListContents = new javax.swing.JList<>();
        infoLbl = new javax.swing.JLabel();
        infoTxtArea = new javax.swing.JScrollPane();
        infoContents = new javax.swing.JTextArea();
        sharedSongsLbl = new javax.swing.JLabel();
        sharedSongsList = new javax.swing.JScrollPane();
        sharedSongsListContents = new javax.swing.JList<>();
        playBtn = new javax.swing.JButton();
        postSection = new javax.swing.JPanel();
        friendsPostLbl = new javax.swing.JLabel();
        postList = new javax.swing.JScrollPane();
        postListContents = new javax.swing.JTextArea();
        postLbl = new javax.swing.JLabel();
        postTxtFld = new javax.swing.JTextField();
        postBtn = new javax.swing.JButton();
        requestSection = new javax.swing.JPanel();
        connectedPeopleListLbl = new javax.swing.JLabel();
        connectedPeopleList = new javax.swing.JScrollPane();
        connectedPeopleListContents = new javax.swing.JList<>();
        requestFriendshipBtn = new javax.swing.JButton();
        chatBtn = new javax.swing.JButton();
        friendshipRequestLbl = new javax.swing.JLabel();
        friendshipRequestList = new javax.swing.JScrollPane();
        friendshipRequestListContents = new javax.swing.JList<>();
        acceptBtn = new javax.swing.JButton();
        refuseBtn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(645, 708));

        parentPanel.setPreferredSize(new java.awt.Dimension(600, 700));
        parentPanel.setLayout(new java.awt.CardLayout());

        loginPanel.setPreferredSize(new java.awt.Dimension(600, 700));

        usernameLbl.setText("Username:");

        goToRegisterBtn.setText("Register");
        goToRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToRegisterBtnActionPerformed(evt);
            }
        });

        passwordLbl.setText("Password:");

        usernameTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtFldActionPerformed(evt);
            }
        });

        passwordTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtFldActionPerformed(evt);
            }
        });

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(loginBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(goToRegisterBtn))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLbl)
                            .addComponent(passwordLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordTxtFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        loginPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {goToRegisterBtn, loginBtn});

        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLbl)
                    .addComponent(usernameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLbl))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goToRegisterBtn)
                    .addComponent(loginBtn))
                .addContainerGap(376, Short.MAX_VALUE))
        );

        parentPanel.add(loginPanel, "card3");

        registerPanel.setPreferredSize(new java.awt.Dimension(600, 700));

        rUsernameLbl.setText("Username");

        backToLoginBtn.setText("Back to Login");
        backToLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToLoginBtnActionPerformed(evt);
            }
        });

        registerBtn.setText("Register");

        orLbl.setText("or");

        PoBLbl.setText("Place of Birth:");

        DoBLbl.setText("Date of Birth:");

        musicDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rap", "R'n'B", "Pop", "Folk", "Acoustic", "Opera", "Rock", " " }));
        musicDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicDropdownActionPerformed(evt);
            }
        });

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        musicProfileLbl.setText("Music Profile");

        jList1.setModel(registerListModel);
        jScrollPane2.setViewportView(jList1);

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addComponent(registerBtn)
                        .addGap(18, 18, 18)
                        .addComponent(orLbl)
                        .addGap(18, 18, 18)
                        .addComponent(backToLoginBtn))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PoBLbl)
                            .addComponent(rUsernameLbl)
                            .addComponent(DoBLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rUsernameTxtFld)
                            .addComponent(PoBTxtFld)
                            .addComponent(DoBTxtFld))))
                .addGap(48, 48, 48)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteBtn))
                    .addComponent(musicProfileLbl)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(musicDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        registerPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {backToLoginBtn, registerBtn});

        registerPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addBtn, deleteBtn});

        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(musicProfileLbl)
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rUsernameLbl)
                    .addComponent(rUsernameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musicDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PoBLbl)
                            .addComponent(PoBTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DoBLbl)
                            .addComponent(DoBTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backToLoginBtn)
                            .addComponent(registerBtn)
                            .addComponent(orLbl))
                        .addGap(54, 54, 54))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addComponent(deleteBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        parentPanel.add(registerPanel, "card2");

        homePanel.setPreferredSize(new java.awt.Dimension(600, 700));

        friendSection.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        friendsLbl.setText("Friends");

        friendsListContents.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Dan", "Taran", "Tom ", "Emil" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        friendsList.setViewportView(friendsListContents);

        infoLbl.setText("Information");

        infoContents.setColumns(20);
        infoContents.setRows(5);
        infoTxtArea.setViewportView(infoContents);

        sharedSongsLbl.setText("Shared Songs");

        sharedSongsListContents.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Let it go (Frozen)", "Shape of you (Ed Sheeran)", "Shut up (Stromzy)" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        sharedSongsList.setViewportView(sharedSongsListContents);

        playBtn.setText("Play");
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout friendSectionLayout = new javax.swing.GroupLayout(friendSection);
        friendSection.setLayout(friendSectionLayout);
        friendSectionLayout.setHorizontalGroup(
            friendSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(friendSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(friendSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(friendSectionLayout.createSequentialGroup()
                        .addComponent(friendsLbl)
                        .addGap(135, 135, 135)
                        .addComponent(infoLbl)
                        .addGap(120, 120, 120)
                        .addComponent(sharedSongsLbl)
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addGroup(friendSectionLayout.createSequentialGroup()
                        .addComponent(friendsList, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(infoTxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(friendSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sharedSongsList))))
                .addContainerGap())
        );
        friendSectionLayout.setVerticalGroup(
            friendSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(friendSectionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(friendSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(friendsLbl)
                    .addComponent(infoLbl)
                    .addComponent(sharedSongsLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(friendSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(friendsList, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoTxtArea)
                    .addGroup(friendSectionLayout.createSequentialGroup()
                        .addComponent(sharedSongsList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playBtn)))
                .addContainerGap())
        );

        postSection.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        friendsPostLbl.setText("Friends Posts");

        postListContents.setColumns(20);
        postListContents.setRows(5);
        postList.setViewportView(postListContents);

        postLbl.setText("Post:");

        postTxtFld.setText("What are you listening to?");
        postTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postTxtFldActionPerformed(evt);
            }
        });

        postBtn.setText("Post");
        postBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout postSectionLayout = new javax.swing.GroupLayout(postSection);
        postSection.setLayout(postSectionLayout);
        postSectionLayout.setHorizontalGroup(
            postSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(postSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(postList)
                    .addGroup(postSectionLayout.createSequentialGroup()
                        .addComponent(friendsPostLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(postSectionLayout.createSequentialGroup()
                        .addComponent(postLbl)
                        .addGap(18, 18, 18)
                        .addComponent(postTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(postBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)))
                .addContainerGap())
        );
        postSectionLayout.setVerticalGroup(
            postSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(friendsPostLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postList, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(postSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postLbl)
                    .addComponent(postTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postBtn))
                .addContainerGap())
        );

        requestSection.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        connectedPeopleListLbl.setText("List of Connected People");

        connectedPeopleListContents.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        connectedPeopleList.setViewportView(connectedPeopleListContents);

        requestFriendshipBtn.setText("Request \nFriendship");
        requestFriendshipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestFriendshipBtnActionPerformed(evt);
            }
        });

        chatBtn.setText("Chat");

        friendshipRequestLbl.setText("Friendship Request from");

        friendshipRequestListContents.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        friendshipRequestList.setViewportView(friendshipRequestListContents);

        acceptBtn.setText("Accept");

        refuseBtn.setText("Refuse");

        javax.swing.GroupLayout requestSectionLayout = new javax.swing.GroupLayout(requestSection);
        requestSection.setLayout(requestSectionLayout);
        requestSectionLayout.setHorizontalGroup(
            requestSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(requestSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(connectedPeopleListLbl)
                    .addGroup(requestSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, requestSectionLayout.createSequentialGroup()
                            .addComponent(requestFriendshipBtn)
                            .addGap(18, 18, 18)
                            .addComponent(chatBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(connectedPeopleList, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(requestSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(friendshipRequestList)
                    .addGroup(requestSectionLayout.createSequentialGroup()
                        .addComponent(friendshipRequestLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(requestSectionLayout.createSequentialGroup()
                        .addComponent(acceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refuseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        requestSectionLayout.setVerticalGroup(
            requestSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(requestSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connectedPeopleListLbl)
                    .addComponent(friendshipRequestLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(requestSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(friendshipRequestList, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(connectedPeopleList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(requestSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestFriendshipBtn)
                    .addComponent(chatBtn)
                    .addComponent(acceptBtn)
                    .addComponent(refuseBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(postSection, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(friendSection, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(requestSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(friendSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(postSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(requestSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        parentPanel.add(homePanel, "card4");

        getContentPane().add(parentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goToRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToRegisterBtnActionPerformed
        //Change screen from login to register
        parentPanel.removeAll();
        parentPanel.add(registerPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_goToRegisterBtnActionPerformed

    private void backToLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToLoginBtnActionPerformed
        //Change screen from register to login
        parentPanel.removeAll();
        parentPanel.add(loginPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_backToLoginBtnActionPerformed

    private void passwordTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtFldActionPerformed

    private void usernameTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxtFldActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        //Adding items to the register panel list
        String genre = musicDropdown.getSelectedItem().toString();
        registerListModel.addElement(genre);
    }//GEN-LAST:event_addBtnActionPerformed

    private void postBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postBtnActionPerformed

    private void postTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postTxtFldActionPerformed

    private void requestFriendshipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestFriendshipBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestFriendshipBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        //take the user input (username and password) and compare it to the file to check if they exist
        
        //Change screen from login to home
        parentPanel.removeAll();
        parentPanel.add(homePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_loginBtnActionPerformed

    private void musicDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musicDropdownActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playBtnActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new window().setVisible(true);            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DoBLbl;
    private javax.swing.JTextField DoBTxtFld;
    private javax.swing.JLabel PoBLbl;
    private javax.swing.JTextField PoBTxtFld;
    private javax.swing.JButton acceptBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backToLoginBtn;
    private javax.swing.JButton chatBtn;
    private javax.swing.JScrollPane connectedPeopleList;
    private javax.swing.JList<String> connectedPeopleListContents;
    private javax.swing.JLabel connectedPeopleListLbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JPanel friendSection;
    private javax.swing.JLabel friendsLbl;
    private javax.swing.JScrollPane friendsList;
    private javax.swing.JList<String> friendsListContents;
    private javax.swing.JLabel friendsPostLbl;
    private javax.swing.JLabel friendshipRequestLbl;
    private javax.swing.JScrollPane friendshipRequestList;
    private javax.swing.JList<String> friendshipRequestListContents;
    private javax.swing.JButton goToRegisterBtn;
    private javax.swing.JPanel homePanel;
    private javax.swing.JTextArea infoContents;
    private javax.swing.JLabel infoLbl;
    private javax.swing.JScrollPane infoTxtArea;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JComboBox<String> musicDropdown;
    private javax.swing.JLabel musicProfileLbl;
    private javax.swing.JLabel orLbl;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JTextField passwordTxtFld;
    private javax.swing.JButton playBtn;
    private javax.swing.JButton postBtn;
    private javax.swing.JLabel postLbl;
    private javax.swing.JScrollPane postList;
    private javax.swing.JTextArea postListContents;
    private javax.swing.JPanel postSection;
    private javax.swing.JTextField postTxtFld;
    private javax.swing.JLabel rUsernameLbl;
    private javax.swing.JTextField rUsernameTxtFld;
    private javax.swing.JButton refuseBtn;
    private javax.swing.JButton registerBtn;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JButton requestFriendshipBtn;
    private javax.swing.JPanel requestSection;
    private javax.swing.JLabel sharedSongsLbl;
    private javax.swing.JScrollPane sharedSongsList;
    private javax.swing.JList<String> sharedSongsListContents;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTxtFld;
    // End of variables declaration//GEN-END:variables
}
